$(document).ready(function($) {
  var quotes = [
    "Yesterday, you said tomorrow.",
    "Don't compare your beginning to someone else's middle.",
    "The wisest mind has something yet to learn.",
    "Be the change you wish to see in the world. - Gandhi",
    "When you're going through hell, keep going. - Winston Churchill",
    "Don't let perfection become procrastination. Do it now.",
    "Launch and learn. Everything is progress.",
    "A year from now you will wish you had started today. - Karen Lamb",
    "Failure is success if you learn from it.",
    "If you don't like where you are, change it.",
    "If it ain't fun, don't do it.",
    "A wet man does not fear the rain.",
    "Stay hungry; stay foolish.",
    "No one saves us but ourselves. No one can and no one may. We ourselves must walk the path. - Buddha",
    "Never give up. Never let things out of your control dictate who you are.",
    "Be kind; everyone you meet is fighting a hard battle.",
    "Impossible is just a big word thrown around by small men who find it easier to live in the world they've been given than to explore the power they have to change it.",
    "People who are unable to motivate themselves must be content with mediocrity no matter how impressive their other talents. - Andrew Carnegie",
    "Progress is impossible without change, and those who cannot change their minds cannot change anything.",
    "Do more of what makes you happy.",
    "Do a little more of what you want to do every day, until your idea becomes what's real.",
    "You got this. Make it happen.",
    "Don't blame others as an excuse for your not working hard enough.",
    "Care about what other people think and you will always be their prisoner. - Lao Tzu",
    "To escape criticism: do nothing, say nothing, be nothing.",
    "The world is moving so fast that the man who says it can't be done is generally interrupted by someone doing it. - Elbert Hubbard",
    "Be who you are and say what you feel, because those who mind don't matter and those who matter don't mind. - Elbert Hubbard",
    "One day you will wake up and there won't be any more time to do the things you've always wanted. Do it now. - Paulo Coelho",
    "Never waste a minute thinking about people you don't like. - Dwight Eisenhower",
    "Never let your fear decide your fate.",
    "Keep moving forward. One step at a time.",
    "Life is simple. Are you happy? Yes? Keep going. No? Change something.",
    "The journey of a thousand miles begins with a single step.",
    "First they ignore you, then they laugh at you, then they fight you, then you win.",
    "A man is but the product of his thoughts. What he thinks, he becomes. - Gandhi",
    "Live as if you were to die tomorrow. Learn as if you were to live forever. - Gandhi",
    "The future depends on what we do in the present. - Gandhi",
    "I am strong because I've been weak. I am fearless because I've been afraid. I am wise, because I've been foolish.",
    "Believe in yourself.",
    "Lower the cost of failure.",
    "Keep your goals away from the trolls.",
    "Respect yourself enough to walk away from anything that no longer serves you, grows you, or makes you happy. - Robert Tew",
    "Everything around you that you call life was made up by people, and you can change it.",
    "In times of change, learners inherit the earth, while the learned find themselves beautifully equipped to deal with a world that no longer exists.",
    "If you fear failure, you will never go anywhere.",
    "Go ahead, let them judge you.",
    "The world breaks everyone and afterward many are strong at the broken places.",
    "The only disability in life is a bad attitude.",
    "If most of us are ashamed of shabby clothes and shoddy furniture, let us be more ashamed of shabby ideas and shoddy philosophies. - Einstein",
    "It is no measure of health to be well adjusted to a profoundly sick society. - Krishnamurti",
    "Think lightly of yourself and deeply of the world. - Miyamoto Musashi",
    "Dude, suckin' at something is the first step to being sorta good at something.",
    "As you think, so shall you become.",
    "Do not wish for an easy life. Wish for the strength to endure a difficult one. - Bruce Lee",
    "Showing off is the fool's idea of glory. - Bruce Lee",
    "Use only that which works, and take it from any place you can find it. - Bruce Lee",
    "I'm not in this world to live up to your expectations and you're not in this world to live up to mine. - Bruce Lee",
    "If you spend too much time thinking about a thing, you'll never get it done. - Bruce Lee",
    "Knowing is not enough, we must apply. Willing is not enough, we must do. - Bruce Lee",
    "Empty your cup so that it may be filled; become devoid to gain totality. - Bruce Lee",
    "It's not the daily increase but daily decrease. Hack away at the unessential. - Bruce Lee",
    "Be yourself. Everyone else is already taken. - Oscar Wilde",
    "Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that. - MLK Jr.",
    "Yesterday is history; tomorrow is a mystery. Today is a gift, which is why we call it the present. - Bil Keane",
    "Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world. - Einstein",
    "I have not failed. I've just found 10,000 ways that won't work. - Thomas Edison",
    "When I let go of what I am, I become what I might be.",
    "It is never too late to be what you might have been. - George Eliot",
    "Always be yourself, express yourself, have faith in yourself. Do not go out and look for a successful personality and duplicate it. - Bruce Lee",
    "When you are content to be simply yourself and don't compare or compete, everyone will respect you. - Lao Tzu",
    "If you want to awaken all of humanity, awaken all of yourself. - Lao Tzu",
    "Don't regret anything you do, because in the end it makes you who you are.",
    "Tension is who you think you should be. Relaxation is who you are.",
    "You are confined only by the walls you build yourself.",
    "Unless you try to do something beyond what you have already mastered you will never grow. - Ralph Waldo Emerson",
    "Don't think about what might go wrong, think about what could be right.",
    "What the caterpillar calls the end, the rest of the world calls a butterfly. - Lao Tzu",
    "To be beautiful means to be yourself. You don't need to be accepted by others. You need to be yourself. - Thich Nhat Hanh",
    "Let go of those who bring you down and surround yourself with those who bring out the best in you.",
    "Don't let small minds convince you that your dreams are too big.",
    "If you don't like something, change it. If you can't change it, change your attitude. Don't complain. - Mary Angelou",
    "You can't climb the ladder of success with your hands in your pockets. - Arnold Schwarzenegger",
    "You can feel sore tomorrow or you can feel sorry tomorrow. You choose.",
    "It is more important to know where you are going than to get there quickly. Do not mistake activity for achievement. - Isocrates",
    "There are seven days in the week and someday isn't one of them.",
    "Start where you are. Use what you can. Do what you can. - Arthur Ashe",
    "Dreams don't work unless you do.",
    "When you wake up in the morning you have two choices: go back to sleep, or wake up and chase those dreams.",
    "Everybody comes to a point in their life when they want to quit, but it's what you do at that moment that determines who you are.",
    "This is your life. Do what you love, and do it often.",
    "Live your dream, and wear your passion.",
    "Today I will do what others won't, so tomorrow I can do what others can't.",
    "The biggest room in the world is room for improvement.",
    "If people aren't laughing at your dreams, your dreams aren't big enough.",
    "Never look back unless you are planning to go that way.",
    "Every dream begins with a dreamer. Always remember, you have within you the strength, the patience, and the passion to reach for the stars to change the world.",
    "You are awesome.",
    "Simplicity is the ultimate sophistication.",
    "Anyone who stops learning is old. - Henry Ford",
    "The cure to boredom is curiosity.",
    "Never give up on a dream just because of the time it will take to accomplish it. The time will pass anyway.",
    "It's time to start living the life you've only imagined.",
    "You don't have to live your life the way other people expect you to.",
    "The trouble with not having a goal is that you can spend your life running up and down the field and never score.",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
    "Incredible change happens in your life when you decide to take control of what you do have power over instead of craving control over what you don't.",
    "Do more with less.",
    "Overthinking ruins you. Ruins the situation, twists it around, makes you worry and just makes everything much worse than it actually is.",
    "Replace fear of the unknown with curiosity.",
    "The surest way to find your dream job is to create it.",
    "What you do today is important because you are exchanging a day of your life for it.",
    "One man or woman with courage is a majority.",
    "Do one thing every day that scares you. - Eleanor Roosevelt",
    "Failure is simply the opportunity to begin again, this time more intelligently. - Henry Ford",
    "Don't just wait for inspiration. Become it.",
    "Don't limit your challenges - challenge your limits.",
    "When you judge others, you do not define them; you define yourself. - Wayne Dyer",
    "Time you enjoy wasting is not wasted time.",
    "Do small things with great love.",
    "Go forth and make awesomeness.",
    "Your big opportunity may be right where you are now. - Napoleon Hill",
    "Life begins at the end of your comfort zone.",
    "Excuses are born out of fear. Eliminate your fear and there will be no excuses.",
    "Happiness is not the absence of problems, it's the ability to deal with them.",
    "The problem is not the problem. The problem is your attitude about the problem.",
    "You don't have to be great to start, but you have to start to be great.",
    "Cherish your visions and your dreams as they are the children of your soul, the blueprints of your ultimate achievements.",
    "Decide that you want it more than you are afraid of it.",
    "Adventure may hurt you, but monotony will kill you.",
    "Obsessed is a word that the lazy use to describe the dedicated.",
    "If they can do it, so can you.",
    "Success isn't about being the best. It's about always getting better.",
    "Success is the ability to go from failure to failure without losing your enthusiasm. - Winston Churchill",
    "A pessimist sees the difficulty in every opportunity; an optimist sees the opportunity in every difficulty. - Winston Churchill",
    "Failure is just practice for success.",
    "Shipping beats perfection.",
    "Failure is simply the opportunity to begin again. This time more intelligently.",
    "While we are postponing, life speeds by.",
    "It always seems impossible until it's done.",
    "Don't let the mistakes and disappointments of the past control and direct your future.",
    "It's not about where your starting point is, but your end goal and the journey that will get you there.",
    "Waste no more time arguing about what a good person should be. Be one.",
    "Life shrinks of expands in proportion to one's courage.",
    "Absorb what is useful. Discard what is not. Add what is uniquely your own.",
    "Don't find fault. Find a remedy.",
    "Doubt kills more dreams than failure ever will.",
    "Don't let someone who gave up on their dreams talk you out of going after yours.",
  ]

  $('.quote_content').html('<p>' + quotes[$.cookie("background")] + "</p>")
});
